plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Danyon Spinelli\\Documents\\Important stuff\\Claude\\Projects\\PKMCHMVGC\\champions-companion\\apps\\web"
publishOrigin = "default"
base = "C:\\Users\\Danyon Spinelli\\Documents\\Important stuff\\Claude\\Projects\\PKMCHMVGC\\champions-companion"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]